config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index", as: :start

  devise_scope :users do
    root to: 'devise/sessions#new'
  end

  namespace :api do 
    namespace :v1 do 
      resources :users do
        resources :posts do 
          resources :comments
          resources :likes
        end 
      end
    end
  end

  # Users
  get 'users/:id' => 'users#show', as: :user_id

  # Posts
  get 'users/:user_id/posts' => 'posts#index', as: :all_post
  get 'users/:user_id/posts/new' => 'posts#new', as: :post_new
  post 'users/:user_id/posts/new' => 'posts#create', as: :post
  get 'users/:user_id/posts/:id' => 'posts#show', as: :post_id
  delete 'users/:user_id/posts/:id' => 'posts#destroy'

  #Comments

  get 'users/:user_id/posts/:id/comments/new' => 'comments#new', as: :comments_new
  post 'users/:user_id/posts/:id/comments' => 'comments#create', as: :comment
  delete 'users/:user_id/posts/:id/comment/:comment_id' => 'comments#destroy', as: :comment_destroy

  #likes
  get 'users/:user_id/posts/:id/likes/new' => 'likes#create', as: :likes_create

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.is?(:admin)
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author: user
      can :manage, Comment, author: user
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  after_save :comment_counter

  def comment_counter
    post.update(comments_counter: post.comments.all.length)
  end

  def user(id)
    User.find(id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  before_save :like_counter

  def like_counter
    post.update(likes_counter: post.likes.all.length)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :author, class_name: 'User'
  after_save :post_count
  after_destroy :post_count

  validates :title, presence: true, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def all_comments
    comments.order(created_at: :desc)
  end

  def post_count
    author.update(posts_counter: author.posts.all.length)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable, jwt_revocation_strategy: self
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  ROLES = %i[admin default].freeze
  def is?(requested_role)
    role == requested_role.to_s
  end

  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    comment = Comment.all.where(author_id: params[:user_id], post_id: params[:post_id]).includes(:author)
    render json: comment
  end

  def create
    posts = Post.find(params[:post_id])
    current_user = User.find(params[:user_id])
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id
    comment.post_id = posts.id

    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    post = user.post
    render json: post
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def index
        @all_users = User.all
        @user = current_user
      end

      def show
        @user = User.find(request.parameters[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name])
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(post_id: params[:id], author: current_user, text: params[:text])
    redirect_to post_id_path(current_user.id, params[:id]) if @comment.save
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @comment.destroy
    redirect_to post_id_path(params[:user_id], params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(post_id: params[:id], author: current_user)
    @like.save
    redirect_to post_id_path(current_user.id, params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(request.parameters[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(author: current_user, title: params[:title], text: params[:text])
    if @post.save
      redirect_to start_path
    else
      puts @post.errors.full_messages
    end
  end

  def show
    @post = Post.find(request.parameters[:id])
    @user = User.find(params[:user_id])
  end

  def destroy
    @post = Post.find(request.parameters[:id])
    @post.destroy
    redirect_to all_post_path(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @all_users = User.all
    @user = current_user
  end

  def show
    @user = User.find(request.parameters[:id])
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Comment Here</h1>
<%= form_with model: @comments, url: comment_path do |form| %>
  <%= form.text_area :text %>
  <%= form.submit "Post Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<div class="post-container">
  <% @user.recent_posts.each_with_index do |post, index| %>
    <%= link_to post_id_path(@user, post), class: 'post-card-link' do %>
      <%= render 'shared/post-card', post: post, user: @user, id: post.id, brief: true, comment: true, all: false %>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'form', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1>New Post</h1>
<%= render 'shared/create_post' %>

app/views/posts/show.html.erb
<div class="p-container">
  <%= render 'shared/post-card', post: @post, user: @user, index: @post.id, brief: false, comment: true, all: true %>
  <%= link_to 'Comment ', "#{request.url}/comments/new", class: 'comment-btn' %>
  <%= link_to 'Like ', "#{request.url}/likes/new", class: 'comment-btn' %>
  <% if can? :destroy, @post %>
    <%= button_to 'Delete', post_id_path(@user.id, @post.id), :method => :delete, class: 'btn btn-outline-danger' %>
  <% end %>
</div>

app/views/shared/_create_post.html.erb
<%= stylesheet_link_tag 'form', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= form_with model: @posts do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div> 
  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>
  <div class="form-group">
    <%= form.submit "Create Post" %>
  </div>
<% end %>

app/views/shared/_post-card.html.erb
<%= stylesheet_link_tag 'user_show', media: 'all', 'data-turbolinks-track': 'reload' %>

<li class="post-item card">
  <h3 class="post-item__heading"><%= post.title %></h3>
  <p class="post-item__interactions">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
  <p class="post-item__detail"><%= brief ? post.text[0..120]... : post.text %></p>
</li>

<% if comment %>
  <ul class="post-item__comments-container">
    <% if all %>
      <% post.all_comments.each do |comment| %>
        <li class="post-item__comment">
          <%= comment.user(comment.author_id).name %>: <%= comment.text %>
          <% if can? :destroy, comment %>
            <%= button_to "Delete Comment", comment_destroy_path(@user.id, post.id, comment.id), method: :delete, class: "btn btn-outline-danger" %>
          <% end %>
        </li>
      <% end %>
    <% else %>
      <% post.recent_comments.each do |comment| %>
        <li class="post-item__comment">
          <%= comment.user(comment.author_id).name %>: <%= comment.text %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/shared/_user-card.html.erb
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
<li class="user-list-item">
  <img class="user-list-item__image" src=<%= user.photo %> alt="dummy-image">
    <p class="user-list-item__name"><%= user.name %></p>
    <p class="user-list-item__post-count"><%= user.posts_counter %> Posts</p>
</li>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="navbar">
<img class="userImg" src=<%= @user.photo %> alt="User Image">
<%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary reload" %>
</div>

<% if user_signed_in? %>
  <div class="welcome-section">
    <p class="welcome-header">Welcome <span class="user-name"><%= current_user.name %></span></p>
  </div>
<% end %>

<div class="user-list d-flex flex-wrap">
  <% @all_users.each do |user| %>
    <div class="user-card m-2">
      <%= link_to user_id_path(user.id) do %>
        <%= render partial: 'shared/user-card', locals: { user: user } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user_show', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="cardx">
  <%= render 'shared/user-card', user: @user %>
</div> 
<ul class="user-details">
<div class="bio-section card">
    <h2 class="bio-heading">Bio</h2>
    <p class="bio-text"><%= @user.bio %></p>
</div>

  <%# <%= link_to "Add New Post", "/users/#{@user.id}/posts/new", {:class => "see_all_post"}%>
 <%= link_to 'Create a Post ', post_new_path(@user.id), class: 'comment-btn' %>

<ul class="post-list">
  <% @user.recent_posts.each_with_index do |post, index| %>
   <%= render 'shared/post-card', post: post, user: @user,index: post.id, brief: true, comment: false, all: false %>
  <% end %>
</ul>
  <%= link_to 'See All Posts', "#{@user.id}/posts", class: 'link-btn' %>
</ul>